### ISSUE TITLE
Not showing anything with a gray screen

### ISSUE THREAD

**Issue by beedrill** [orhanemree/MEVN-Stack-Blog#1]
The error from the console as follows:
vue-router.esm-bundler.js:3295 TypeError: Cannot read properties of null (reading 'loggedIn')
    at index.js:53:70
    at vue-router.esm-bundler.js:1930:35
    at new Promise (<anonymous>)
    at vue-router.esm-bundler.js:1904:18
    at vue-router.esm-bundler.js:3412:65

**Comment by Ariiima** [comment]
same issue
